// Generated by https://quicktype.io

export interface PeliculasResponse {
    dates:         Dates;
    page:          number;
    results:       Pelicula[];
    total_pages:   number;
    total_results: number;
}

export interface Dates {
    maximum: string;
    minimum: string;
}

export interface Pelicula {
    adult:             boolean;
    backdrop_path:     string;
    genre_ids:         number[];
    id:                number;
    original_language: OriginalLanguage;
    original_title:    string;
    overview:          string;
    popularity:        number;
    poster_path:       string;
    release_date:      string;
    title:             string;
    video:             boolean;
    vote_average:      number;
    vote_count:        number;
}

export interface Genero{

    id:                number;
    name:              string;
}
   

export enum OriginalLanguage {
    En = "en",
    Fr = "fr",
    ID = "id",
    Uk = "uk",
}


